(ns aoc2024.day-06-test
  (:require  [aoc2024.day-06 :refer :all]
             [clojure.test :as t]))

(def input-1 "
....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...
")

(t/deftest test-part-1
  (t/is (= 41 (part-1 input-1))))
